-- MySQL Script generated by MySQL Workbench
-- Sat Feb 13 15:56:29 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `validado` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Copisterias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Copisterias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Copisterias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tarifas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tarifas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tarifas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCopisteria` INT NULL,
  `precio_byn` DECIMAL NULL,
  `precio_color` DECIMAL NULL,
  `tiempo` TIME(0) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`idCopisteria` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`idCopisteria`)
    REFERENCES `mydb`.`Copisterias` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trabajos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Trabajos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Trabajos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idTarifa` INT NULL,
  `idUsuario` INT NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`idUsuario` ASC),
  INDEX `id_idx1` (`idTarifa` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`idTarifa`)
    REFERENCES `mydb`.`Tarifas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Archivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Archivos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Archivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idTrabajo` INT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`idTrabajo` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`idTrabajo`)
    REFERENCES `mydb`.`Trabajos` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin_copisterias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Admin_copisterias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Admin_copisterias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCopisteria` INT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`idCopisteria` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`idCopisteria`)
    REFERENCES `mydb`.`Copisterias` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Valoracion_copisterias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Valoracion_copisterias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Valoracion_copisterias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCopisteria` INT NULL,
  `idUsuario` INT NULL,
  `valoracion` DECIMAL NULL,
  `texto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`idUsuario` ASC),
  INDEX `id_idx1` (`idCopisteria` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`idCopisteria`)
    REFERENCES `mydb`.`Copisterias` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Valoracion_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Valoracion_usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Valoracion_usuarios` (
  `id` INT NOT NULL,
  `idUsuario` INT NULL,
  `idCopisteria` INT NULL,
  `valoracion` DECIMAL NULL,
  `texto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`idUsuario` ASC),
  INDEX `id_idx1` (`idCopisteria` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`idCopisteria`)
    REFERENCES `mydb`.`Copisterias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
